"""empty message

Revision ID: 3dd02df91598
Revises: a0d85b9fa75d
Create Date: 2016-07-18 01:09:00.566000

"""

# revision identifiers, used by Alembic.
revision = '3dd02df91598'
down_revision = 'a0d85b9fa75d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lerg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('refresh_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lerg')
    ### end Alembic commands ###
